### ISSUE TITLE
WCAG - Legg til lenketekst logo

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/dcat-ap-no-validator-gui#101]
**What It Means**
A link contains no text.

**Why It Matters**
If a link contains no text, the function or purpose of the link will not be presented to the user. This can introduce confusion for keyboard and screen reader users.

**How to Fix It**
Remove the empty link or provide text within the link that describes the functionality and/or target of that link.

**Comment by hegeaal** [comment]
Already fixed
