### ISSUE TITLE
Legge til Beta-tag for validator-gui

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/dcat-ap-no-validator-gui#14]
Ref design:
https://eggedosis.github.io/fdk-design/redirects/register/portal/start-default.html

**Comment by jeffreiffers** [comment]
Har vi design på dette?

**Comment by shenluna** [comment]
Testet i staging
![image](https://user-images.githubusercontent.com/73637969/106257540-fa20ec00-621c-11eb-8c04-a54a38d3da2e.png)
