### ISSUE TITLE
User should be able to send in shacl-rules to be used in validation with design v1

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dcat-ap-no-validator-gui#19]
NB! Mangler design. Involverer Lene

- [ ] refaktorere shape-id 

- [ ] flytte innstillinger og shacl-rules til ett panel
- [ ] kun advanced del skal være collapseable

Moved features to https://github.com/Informasjonsforvaltning/dcat-ap-no-validator-gui/issues/35.

**Comment by jeffreiffers** [comment]
Flytting av regelgraf og innstillinger til avansert panel skal designes av Lene. Avventer designet.

**Comment by shenluna** [comment]
Testet og verifisert. Nytt design med flytting av regelgraf og innstillinger i eget panel er skilt ut. Ref https://github.com/Informasjonsforvaltning/dcat-ap-no-validator-gui/issues/35
