### ISSUE TITLE
Vise hvilken verdi som feiler

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/dcat-ap-no-validator-gui#20]
I nåværende versjon av prod.satte validatoren, er det ikke mulig å se hvilken verdi som feiler. 

F.eks. `:exDataset dct:theme "tulletema" .` skal gi violation. Da er det fint å ha verdien "tulletema" også vist i feilmeldingen, i tillegg til egenskapen "...dcat#theme".

**Comment by shenluna** [comment]
Testet i staging

![image](https://user-images.githubusercontent.com/73637969/106453470-ac5ceb80-6489-11eb-9038-e503a35bcfce.png)
