### ISSUE TITLE
Bedre feilmeldinger

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/dcat-ap-no-validator-gui#33]
Ved validering med regelgraf som kode får man feilmedling om at shapesgraf URL er feil
- [ ] Fjerne URL
- [ ] Være konsekvent med regelgraf eller shapesgraf
![image.png](https://images.zenhubusercontent.com/5f9a823ccff8726db3db553b/f388f039-1386-4197-9ad2-1281346760bb)

**Comment by jeffreiffers** [comment]
Kan denne lukkes?

**Comment by shenluna** [comment]
Feilmeldingene er endret. Lukker saken
