### ISSUE TITLE
Hvilken regelgraf blir brukt?

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/dcat-ap-no-validator-gui#34]
Når man velger en annen regelgraf input enn default blir filen fremdels validert med default graf

Alternative løsninger
- Ikke mulig å trykke valider før regelgraf fra filopplaster, lenke eller tekst har verdi
- Feilmelding om at regelgrafen ikke er gyldig

![image](https://user-images.githubusercontent.com/73637969/110120750-c017ac80-7dbd-11eb-9a2f-cee0ab0ef900.png)

**Comment by jeffreiffers** [comment]
Kan denne lukkes?

**Comment by shenluna** [comment]
Testet OK.
Ikke lenger mulig å trykke på valider før regelgraf har en verdi.
