### ISSUE TITLE
Violation blir ikkje presentert i gui

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dcat-ap-no-validator-gui#44]
For å gjenskape:
Valider lenke (data-graph-url) = https://raw.githubusercontent.com/Informasjonsforvaltning/dcat-ap-no-validator-service/main/tests/files/valid_catalog_with_distribution.ttl
Regelsett lenke (shapes-graph-url) = https://raw.githubusercontent.com/Informasjonsforvaltning/dcat-ap-no/develop/shacl/DCAT-AP-NO-shacl_shapes_2.00.ttl
Resultat som på skjermbildet:
![image](https://user-images.githubusercontent.com/1702357/113872157-eb722a80-97b3-11eb-9d18-1179df916e46.png)

Validation rapport:
```
[] a ns1:ValidationReport ;
    ns1:conforms false ;
    ns1:result [ a ns1:ValidationResult ;
            ns1:focusNode <http://publications.europa.eu/resource/authority/licence> ;
            ns1:resultMessage "Less than 1 values on <http://publications.europa.eu/resource/authority/licence>->dct:title" ;
            ns1:resultPath ns2:title ;
            ns1:resultSeverity ns1:Violation ;
            ns1:sourceConstraintComponent ns1:MinCountConstraintComponent ;
            ns1:sourceShape [ ns1:minCount 1 ;
                    ns1:nodeKind ns1:Literal ;
                    ns1:path ns2:title ;
                    ns1:severity ns1:Violation ] ] .
```
Den er nok relatert til #42 , men her er det ikkje snakk om blanke noder.

**Comment by shenluna** [comment]
Denne blir løst i #42, lukker derfor saken

**Comment by stigbd** [comment]
Usikker på om vi er heilt i mål med denne. Forsøk med følgande fil. Feiler også i staging:

[catalog_with_distributions_json.txt](https://github.com/Informasjonsforvaltning/dcat-ap-no-validator-gui/files/6298693/catalog_with_distributions_json.txt)
