### ISSUE TITLE
Add support for user supplied ontology information in an ontology-graph file/url

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dcat-ap-no-validator-gui#48]
Analogous to functionality related to shapes-graph/url.

ontology-graph should be optional, but default should be to give link to "official ontology information" that will be published alongside the shacl rules of dcat-ap-no.

Reuse design used on shapes-graph.

**Comment by jeffreiffers** [comment]
Hva er lenken?

**Comment by stigbd** [comment]
Kortsiktig fiks:
send inn ny url som følger (analogt som for `data-graph-url`):
ontology-graph-url: https://raw.githubusercontent.com/Informasjonsforvaltning/dcat-ap-no/v2/shacl/ontologies.ttl

**Comment by jeffreiffers** [comment]
Skal disse vises som lenke eller samme som shapes dropdown? Hvis dropdown hva er navnet til ontology resursen?

**Comment by stigbd** [comment]
Godt spørsmål. Eg har omtalt det som "extra ontological information" i openAPI-spekken. Men eg skal lage /ontologies endepunkt (analogt med /shapes) der du får all nødvendig informasjon. Men ber om at vi først hardkoder slik eg skisserte over, før vi går i gang med dropdown etc. Med mindre det er mykje meir arbeid. I så fall bruke "Velg ontologi" i dropdown. og tilsvarande "Ontologi fil/lenke/tekst".

**Comment by jeffreiffers** [comment]
Ja men kan ikke vise urlen i dropdown så trenger et navn/beskrivelse for eks. "Standard ontologi".

**Comment by stigbd** [comment]
Navnet (dct:title) til ontologien er "The ontologies used by DCAT-AP-NO". Alt dette står i https://github.com/Informasjonsforvaltning/dcat-ap-no/blob/develop/shacl/ontologies.ttl
