### ISSUE TITLE
Hent ontologies frå backend

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/dcat-ap-no-validator-gui#55]
Backend har no støtte for å hente ut "default" ontology-graph på `/ontologies` og `/ontologies/{id}`

Samtidig har backend nokre breaking changes:
- feltnavn er endra fra camel case til snake case

**Comment by stigbd** [comment]
PS! Antagelegvis burde eg ha laga DAO med [json styling guide for property names](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format), men eg håpar å kunne ta dette seinare.

**Comment by shenluna** [comment]
Testet OK
